Add misc bins, weather script

diff --git a/i3/.config/i3/blocks/weather b/i3/.config/i3/blocks/weather
--- a/i3/.config/i3/blocks/weather
+++ b/i3/.config/i3/blocks/weather
@@ -1,21 +1,30 @@
-#!/bin/bash
-# Weather Underground feed
+#!/usr/bin/env bash
 
-API_KEY="bc45abbe61e549ba"
+command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.  Aborting."; exit 1; }
+command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.  Aborting."; exit 1; }
 
-URL="http://api.wunderground.com/api/${API_KEY}/conditions/q/CO/Denver.json"
-ICON_SUNNY=""
-ICON_CLOUDY=""
-ICON_RAINY=""
-ICON_STORM=""
-ICON_SNOW=""
-ICON_FOG=""
+APIKEY="88d560ac615964ceefc9d0af5f04b9a6"
+ZIPCODE="80014"
+URL="http://api.openweathermap.org/data/2.5/weather?zip=${ZIPCODE}&units=imperial&APPID=${APIKEY}"
 
-#WEATHER_INFO=$(wget -qO- "${URL}")
-WEATHER_INFO='{ "response": { "version":"0.1", "termsofService":"http://www.wunderground.com/weather/api/d/terms.html", "features": { "conditions": 1 } } , "current_observation": { "image": { "url":"http://icons.wxug.com/graphics/wu2/logo_130x80.png", "title":"Weather Underground", "link":"http://www.wunderground.com" }, "display_location": { "full":"Denver, CO", "city":"Denver", "state":"CO", "state_name":"Colorado", "country":"US", "country_iso3166":"US", "zip":"80201", "magic":"1", "wmo":"99999", "latitude":"39.74000168", "longitude":"-104.98000336", "elevation":"1598.1" }, "observation_location": { "full":"Capitol Hill, Denver, Colorado", "city":"Capitol Hill, Denver", "state":"Colorado", "country":"US", "country_iso3166":"US", "latitude":"39.734711", "longitude":"-104.977921", "elevation":"5331 ft" }, "estimated": { }, "station_id":"KCODENVE218", "observation_time":"Last Updated on February 16, 12:32 PM MST", "observation_time_rfc822":"Thu, 16 Feb 2017 12:32:18 -0700", "observation_epoch":"1487273538", "local_time_rfc822":"Thu, 16 Feb 2017 12:33:03 -0700", "local_epoch":"1487273583", "local_tz_short":"MST", "local_tz_long":"America/Denver", "local_tz_offset":"-0700", "weather":"Clear", "temperature_string":"70.5 F (21.4 C)", "temp_f":70.5, "temp_c":21.4, "relative_humidity":"18%", "wind_string":"Calm", "wind_dir":"SW", "wind_degrees":215, "wind_mph":0.0, "wind_gust_mph":0, "wind_kph":0, "wind_gust_kph":0, "pressure_mb":"1004", "pressure_in":"29.67", "pressure_trend":"-", "dewpoint_string":"25 F (-4 C)", "dewpoint_f":25, "dewpoint_c":-4, "heat_index_string":"NA", "heat_index_f":"NA", "heat_index_c":"NA", "windchill_string":"NA", "windchill_f":"NA", "windchill_c":"NA", "feelslike_string":"70.5 F (21.4 C)", "feelslike_f":"70.5", "feelslike_c":"21.4", "visibility_mi":"10.0", "visibility_km":"16.1", "solarradiation":"172", "UV":"1.0","precip_1hr_string":"0.00 in ( 0 mm)", "precip_1hr_in":"0.00", "precip_1hr_metric":" 0", "precip_today_string":"0.00 in (0 mm)", "precip_today_in":"0.00", "precip_today_metric":"0", "icon":"clear", "icon_url":"http://icons.wxug.com/i/c/k/clear.gif", "forecast_url":"http://www.wunderground.com/US/CO/Denver.html", "history_url":"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCODENVE218", "ob_url":"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.734711,-104.977921", "nowcast":"" } }'
+WEATHER_RESPONSE=$(wget -qO- "${URL}")
 
-WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"weather\":\s?\"(.+)\"' | awk -F ':' '{print $1}' | tr -d '"')
-WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp_f\":\s?(.+),' | awk -F ':' '{print $1}')
+WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
+WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.main.temp')
 
-echo "${WEATHER_INFO}" | grep -o -e 'weather'
-echo "WEATHER ${WEATHER_MAIN} and ${WEATHER_TEMP}"
+case $WEATHER_CONDITION in
+  'Clouds')
+    WEATHER_ICON=""
+    ;;
+  'Rain')
+    WEATHER_ICON=""
+    ;;
+  'Snow')
+    WEATHER_ICON=""
+    ;;
+  *)
+    WEATHER_ICON=""
+    ;;
+esac
+
+echo "${WEATHER_ICON} ${WEATHER_CONDITION}: ${WEATHER_TEMP}°F"
